fix(hightlight): do not try to highlight non strings
SpoonX/aurelia-autocomplete pull request #18
Opened 2017-01-13 10:23 UTC by bas080

2017-01-13 14:01 UTC, RWOverdijk requested changes

2017-01-13 14:01 UTC, RWOverdijk commented on src/component/autocomplete.js
> +    return result ? result[this.attribute] : '';
```js
@bindable label = result => {
  if (typeof result === 'object' && result !== null && result[this.attribute]) {
    return result[this.attribute];
  }

  return '';
}
```

2017-01-16 10:07 UTC, VMBindraban commented on src/component/autocomplete.js
> +      return ' ';
Is this space needed?

2017-01-16 14:09 UTC, bas080 commented on src/component/autocomplete.js
> +      return ' ';
An alternative could be that it returns the string `no label`

2017-01-19 12:05 UTC, ppvg commented on src/component/autocomplete.js
> +      : '';
These elaborate checks on `result` are not necessary if you need to check whether `result[this.attribute]` exists anyway. A simple truthyness check and short circuit should suffice:

```js
return (result && result[this.attribute]) || '';
```

2017-01-19 12:05 UTC, ppvg commented on src/component/autocomplete.js
> +      return ' ';
So why can't it be an empty string? If it's a workaround, either fix the issue or document why the workaround is needed.

2017-01-25 11:11 UTC, bas080 commented on src/component/autocomplete.js
> +      return ' ';
I will document that the reason for this is because it avoids the element not getting the proper height.

2017-01-25 11:15 UTC, bas080 commented
@ppvg, implemented feedback.

2017-01-25 22:41 UTC, RWOverdijk commented
@bas080 Is this still needed with all the changes in the other PR? I'm pretty sure I covered these, too. Closing for now.

2017-01-25 22:41 UTC, closed without merging