feat(project): add items bindable
SpoonX/aurelia-autocomplete pull request #2
Opened 2016-12-21 16:07 UTC by bas080

This enables users to use and array with values to auto-complete on. When using
this bindable it disables the performing of requests.

Contains the necessary documentation which explains what methods can be
overwritten and the newly defined items bindable. Also updated the altered
bindables behavior documentation

2016-12-23 13:43 UTC, RWOverdijk requested changes

2016-12-23 13:43 UTC, RWOverdijk commented on src/component/autocomplete.js
> +    this.justSelected = true;
Sloppy code style

2016-12-23 13:43 UTC, RWOverdijk commented on src/component/autocomplete.js
> +   * returns HTML that wraps matching substrings with strong tags. If not
Cut on new sentence or append on the end.

2016-12-23 13:43 UTC, RWOverdijk commented on src/component/autocomplete.js
> +    this.dropdownElement = this.element.querySelectorAll('.dropdown.open')[0];
Why is this still needed?

2016-12-23 15:19 UTC, bas080 commented on src/component/autocomplete.js
> +    this.dropdownElement = this.element.querySelectorAll('.dropdown.open')[0];
Because bootstrap.js will add and remove the open class for you

2017-01-03 09:22 UTC, RWOverdijk requested changes

2017-01-03 09:22 UTC, RWOverdijk commented on src/component/autocomplete.js
> +
Remove newline

2017-01-03 09:22 UTC, RWOverdijk commented on src/component/autocomplete.js
> +    let promise = this.findResults(this.searchQuery(this.search)).then(results => {
Why not use: `this.lastFindPromise = ....`?

It's a sync process as far as I can see, so the assignment is basically the same, isn't it?

2017-01-03 14:39 UTC, bas080 commented on src/component/autocomplete.js
> +    let promise = this.findResults(this.searchQuery(this.search)).then(results => {
that's correct

2017-01-09 14:57 UTC, RWOverdijk commented
@VMBindraban and @jeremyvergnas please review.

2017-01-09 16:43 UTC, jeremyvergnas commented on src/component/autocomplete.js
> +      if (this.lastFindPromise !== promise) {
Can be removed I guess

2017-01-11 10:00 UTC, merged