fix(project): prevent autocomplete options from being uncollapsed ini…
SpoonX/aurelia-autocomplete pull request #52
Opened 2018-03-26 18:01 UTC by Mobe91

Fixes #51

2018-04-10 07:46 UTC, RWOverdijk requested changes

2018-04-10 07:46 UTC, RWOverdijk commented on src/component/autocomplete.js
>      if (!this.shouldPerformRequest()) {
Newline between if and let.

2018-04-18 13:19 UTC, Mobe91 commented
@RWOverdijk Are there any other changes required for this PR?

2018-04-19 08:53 UTC, RWOverdijk commented
I should test this but I'm quite overwhelmed with work. I;'ll push this onto the prerelease as well, and create a new issue to collect feedback.

2018-04-19 08:54 UTC, merged